-- schema.sql Michael C. Clark 1.07.2015

-- SOME INCONSISTENCIES BETWEEN HSQL AND MSSQL
-- DEFAULT ((-1)) --> DEFAULT -1
-- GETDATE() --> CURRENT_TIMESTAMP

-- FOREIGN KEYS TO EXISTING WFC TABLES OMITTED

SET DATABASE SQL SYNTAX MSS TRUE;

CREATE FUNCTION GETDATE() RETURNS TIMESTAMP(3) RETURN LOCALTIMESTAMP(3);

--CREATE SCHEMA dbo;


CREATE TABLE AUTHOR
(
  ID BIGINT NOT NULL,
  FNAME CHARACTER VARYING(256) UNIQUE NOT NULL CHECK (FNAME <> ''),
  LNAME CHARACTER VARYING(256) UNIQUE NOT NULL CHECK (LNAME <> ''),
  EMAIL CHARACTER VARYING(256) UNIQUE NOT NULL CHECK (EMAIL <> ''),
  CONSTRAINT AUTHOR_PKEY PRIMARY KEY (ID)
);
CREATE TABLE MEMBER
(
  ID BIGINT NOT NULL,
  FNAME CHARACTER VARYING(256) UNIQUE NOT NULL CHECK (FNAME <> ''),
  LNAME CHARACTER VARYING(256) UNIQUE NOT NULL CHECK (LNAME <> ''),
  EMAIL CHARACTER VARYING(256) UNIQUE NOT NULL CHECK (EMAIL <> ''),
  CONSTRAINT MEMBER_PKEY PRIMARY KEY (ID)
);
CREATE TABLE BOOK
(
  ID BIGINT NOT NULL,
  TITLE CHARACTER VARYING(256) UNIQUE NOT NULL CHECK (TITLE <> ''),
  PUBLISHER CHARACTER VARYING(256) UNIQUE NOT NULL CHECK (PUBLISHER <> ''),
  ISBN CHARACTER VARYING(256) UNIQUE NOT NULL CHECK (ISBN <> ''),
  CONSTRAINT BOOK_PKEY PRIMARY KEY (ID)
);
CREATE TABLE BOOK_AUTHOR
(
  ID BIGINT NOT NULL,
  BOOK_ID BIGINT NOT NULL,
    AUTHOR_ID BIGINT NOT NULL,
  CONSTRAINT BOOK_AUTHOR_PKEY PRIMARY KEY (ID),
    CONSTRAINT BOOK_AUTHOR_FKEY1 FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (ID),
  CONSTRAINT BOOK_AUTHOR_FKEY2 FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID)  
);

CREATE TABLE BOOK_COPY
(
  ID BIGINT NOT NULL,
  BOOK_ID BIGINT NOT NULL,
    IS_BORROWED BOOLEAN NOT NULL,
    BORROW_COUNT BIGINT NOT NULL,
  CONSTRAINT BOOK_COPY_PKEY PRIMARY KEY (ID),
  CONSTRAINT BOOK_COPY_FKEY2 FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID)  
);
CREATE TABLE MEMBER_COPY
(
  ID BIGINT NOT NULL,
  BOOK_COPY_ID BIGINT NOT NULL,
    MEMBER_ID BIGINT NOT NULL,
    DATE_OF_BORROW TIMESTAMP NOT NULL,
  CONSTRAINT MEMBER_COPY_PKEY PRIMARY KEY (ID),
  CONSTRAINT MEMBER_COPY_FKEY2 FOREIGN KEY (BOOK_COPY_ID) REFERENCES BOOK_COPY (ID),  
    CONSTRAINT MEMBER_COPY_FKEY3 FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (ID)  
);
CREATE SEQUENCE AUTHOR_SEQUENCE
MINVALUE 1
START WITH 1
INCREMENT BY 1;
CREATE SEQUENCE MEMBER_SEQUENCE
MINVALUE 1
START WITH 1
INCREMENT BY 1;
CREATE SEQUENCE BOOK_SEQUENCE
MINVALUE 1
START WITH 1
INCREMENT BY 1;
CREATE SEQUENCE BOOK_AUTHOR_SEQUENCE
MINVALUE 1
START WITH 1
INCREMENT BY 1;
CREATE SEQUENCE BOOK_COPY_SEQUENCE
MINVALUE 1
START WITH 1
INCREMENT BY 1;
CREATE SEQUENCE MEMBER_COPY_SEQUENCE
MINVALUE 1
START WITH 1
INCREMENT BY 1;